pipeline {
  agent any
  stages {
    stage('Build and Test') {
      parallel {
        stage('Check pre-commit requirements') {
          agent {
            docker {
              image 'oetools-azure:1.7'
            }
          }
          steps {
            timeout(2) {
              sh './scripts/check-precommit-reqs'
            }
          }
        }
        stage('Windows Debug Cross-platform') {
          stages {
            stage('Linux SGX1 Debug') {
              agent {
                docker {
                  image 'oetools-azure:1.7'
                }
              }
              steps {
                timeout(15) {
                  sh './scripts/test-build-config -p SGX1FLC -b Debug --compiler=clang-7'
                  stash includes: 'build/tests/**', name: 'linuxdebug'
                }
              }
            }
            stage('Windows Debug') {
              agent {
                node {
                  label 'SGXFLC-Windows'
                }
              }
              steps {
                unstash 'linuxdebug'
                bat 'move build linuxbin'
                bat 'mkdir build && cd build && cmake -G "Visual Studio 15 2017 Win64" -DADD_WINDOWS_ENCLAVE_TESTS=1 -DLINUX_BIN_DIR=%cd%\\linuxbin\\tests .. && pushd . && "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\Common7\\Tools\\LaunchDevCmd.bat" && popd && cmake --build . --config Debug && ctest -V -C Debug'
              }
            }
          }
        }
        stage('Windows Release Cross-platform') {
          stages {
            stage('Linux SGX1 Release') {
              agent {
                docker {
                  image 'oetools-azure:1.7'
                }
              }
              steps {
                timeout(15) {
                  sh './scripts/test-build-config -p SGX1FLC -b Release --compiler=clang-7'
                  stash includes: 'build/tests/**', name: 'linuxrelease'
                }
              }
            }
            stage('Windows Release') {
              agent {
                node {
                  label 'SGXFLC-Windows'
                }
              }
              steps {
                unstash 'linuxrelease'
                bat 'move build linuxbin'
                bat 'mkdir build && cd build && cmake -G "Visual Studio 15 2017 Win64" -DADD_WINDOWS_ENCLAVE_TESTS=1 -DLINUX_BIN_DIR=%cd%\\linuxbin\\tests .. && pushd . && "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\Common7\\Tools\\LaunchDevCmd.bat" && popd && cmake --build . --config Release && ctest -V -C Release'
              }
            }
          }
        }
      }
    }
  }
}


